[package]
name = "cp"
version = "0.0.2"
authors = ["Jordy Dickinson", "Kevin Zander"]

[lib]
name = "uu_cp"
path = "cp.rs"

[dependencies]
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name = "cp"
path = "main.rs"
